Inserimento segnalazione
benedettoscala/CiviConnect pull request #10
Opened 2024-12-06 09:19 UTC by GiuseppeGambardella

## Descrizione delle Modifiche nel Branch `inserimento-segnalazione`

In questo branch è stato implementato il sistema di **inserimento segnalazioni**, con le seguenti funzionalità principali:

### 1. Inserimento della Segnalazione
- È stata creata un'interfaccia che consente agli utenti di inserire i dettagli delle segnalazioni, fornendo un sistema semplice e intuitivo.

### 2. Geolocalizzazione
- L'utente ha la possibilità di associare la segnalazione alla propria posizione geografica attuale.
- È stata implementata la gestione della geolocalizzazione utilizzando le API di localizzazione disponibili.

### 3. Richiesta di Permessi
- Il sistema richiede dinamicamente i permessi necessari per accedere alla posizione dell'utente.
- È stata inclusa una gestione robusta dei permessi, con feedback visivo in caso di rifiuto o errore.

### 4. Immagini a Scopo Illustrativo
- Sono state incluse immagini di esempio per rappresentare visivamente le funzionalità.
- **Nota**: Le immagini sono esclusivamente illustrative, poiché non è stato possibile implementare una gestione avanzata delle immagini a causa di vincoli economici.

2024-12-06 09:45 UTC, Type-Here commented on src/lib/gestione_segnalazione_cittadino/gestione_segnalazione_cittadino_DAO.dart
> +      throw Exception('Failed to add report');
is this exception catched somewhere else?  
remove print in production code

2024-12-06 09:49 UTC, Type-Here commented on src/lib/gestione_segnalazione_cittadino/inserimento_segnalazione_gui.dart
> +  late Map<String, String>? _indirizzo;
think about removing late

2024-12-06 09:52 UTC, Type-Here commented on src/lib/gestione_segnalazione_cittadino/inserimento_segnalazione_gui.dart
> +            decoration: TextFieldInputDecoration(context, labelText: 'Titolo'),
comparing to rad: volgarity check

2024-12-06 12:57 UTC, Type-Here commented on src/lib/gestione_segnalazione_cittadino/gestione_location_failed.dart
> +  const LocationPermissionPage({super.key, required this.redirectPage});
required param first

2024-12-06 12:57 UTC, Type-Here commented on src/lib/gestione_segnalazione_cittadino/gestione_segnalazione_cittadino_controller.dart
> +    placemarks[0].street ?? "Strada non disponibile",
prefer single quotes

2024-12-06 14:07 UTC, benedettoscala requested changes
Resolve the conflicts, than you are free to merge!

2024-12-06 14:09 UTC, Luigi11162 requested changes
Resolve conflicts of merge

2024-12-06 15:19 UTC, GiuseppeGambardella commented on src/lib/gestione_segnalazione_cittadino/inserimento_segnalazione_gui.dart
> +  late Map<String, String>? _indirizzo;
the call is asynchronous, late is required

2024-12-06 20:19 UTC, Marco-Brescia reviewed
I think layout could be better, but what you have produced is not bad.

2024-12-07 00:32 UTC, Type-Here requested changes
- Resolve missing features
- Clean up code otherwise build in CI/CD will fail

2024-12-07 00:32 UTC, Type-Here commented on src/lib/gestione_segnalazione_cittadino/inserimento_segnalazione_gui.dart
> +        descrizione: _descrizione!,
Missing info like authorFirstName and authorLastName

2024-12-07 00:32 UTC, Type-Here commented on src/lib/gestione_segnalazione_cittadino/inserimento_segnalazione_gui.dart
> +  late Map<String, String>? _indirizzo;
actually on nullable variables late is not necessary and sometimes redundant see also: [Null Safety](https://www.dhiwise.com/post/avoiding-the-billion-dollar-mistake-in-flutter-understanding-dart-null-safety)

2024-12-07 00:32 UTC, Type-Here commented on src/lib/gestione_segnalazione_cittadino/inserimento_segnalazione_gui.dart
> +import 'package:cloud_firestore/cloud_firestore.dart';
remove unused import

2024-12-07 00:32 UTC, Type-Here commented on src/lib/gestione_segnalazione_cittadino/inserimento_segnalazione_gui.dart
> +                }),
realign code and clean up: did you run flutter analyze and dart fix?

2024-12-07 00:56 UTC, Type-Here commented on src/lib/gestione_segnalazione_cittadino/gestione_segnalazione_cittadino_controller.dart
> +_redirectToLocationPermissionPage(BuildContext context) {
missing return value

2024-12-07 11:34 UTC, Luigi11162 approved these changes
No conflicts. Approved

2024-12-07 12:15 UTC, benedettoscala approved these changes
Approved!

2024-12-08 18:24 UTC, Type-Here requested changes
When requirements from RAD will be implemented, the branch will be ready to be merged

2024-12-08 18:24 UTC, Type-Here commented on src/lib/gestione_segnalazione_cittadino/gestione_segnalazione_cittadino_controller.dart
>  class CitizenReportManagementController {
merging caused missing docs on lots of methods and class

2024-12-08 18:24 UTC, Type-Here commented on src/lib/gestione_segnalazione_cittadino/inserimento_segnalazione_gui.dart
> +            maxLines: 3,
RAD: Validation Missing as on UC max chars

2024-12-08 18:24 UTC, Type-Here commented on src/lib/gestione_segnalazione_cittadino/inserimento_segnalazione_gui.dart
> +            validator: FormBuilderValidators.required(),
RAD: Validation Missing as on UC max chars

2024-12-09 08:03 UTC, GiuseppeGambardella commented on src/lib/gestione_segnalazione_cittadino/inserimento_segnalazione_gui.dart
> +  late Map<String, String>? _indirizzo;
the variable is not set at the declaration so late is required

2024-12-09 08:09 UTC, GiuseppeGambardella commented on src/lib/gestione_segnalazione_cittadino/inserimento_segnalazione_gui.dart
> +        descrizione: _descrizione!,
author infos are set in the controller, here only the problem data is sent

2024-12-09 17:35 UTC, Marco-Brescia approved these changes
LGTM!

2024-12-09 20:07 UTC, Type-Here approved these changes

2024-12-09 21:07 UTC, merged