Modifica stato segnalazione
benedettoscala/CiviConnect pull request #18
Opened 2024-12-13 01:49 UTC by domyz21

added "edit report status" and added a snackbar to show success or failure when you try to set/change the report status or the report priority

2024-12-13 08:23 UTC, FaiellaFrancesco approved these changes
good job, lgtm

2024-12-13 15:17 UTC, Luigi11162 requested changes
Resolve Conflicts, please

2024-12-13 21:00 UTC, domyz21 commented on src/lib/analisi_dati/analisi_dati_gui.dart
improve formatting

2024-12-13 21:01 UTC, domyz21 commented on src/lib/gestione_segnalazione_comune/gestione_segnalazione_comune_dao.dart
edit report status function

2024-12-13 21:02 UTC, domyz21 commented on src/lib/gestione_segnalazione_comune/dettagli_segnalazione_comune_gui.dart
edit status/priority report gui

2024-12-13 21:03 UTC, domyz21 reviewed
fixed merge problems

2024-12-13 21:15 UTC, Luigi11162 approved these changes
LGTM, conflicts resolved. Approved

2024-12-13 21:16 UTC, benedettoscala approved these changes

2024-12-14 09:41 UTC, Borax-Gargamella approved these changes

2024-12-14 10:30 UTC, merged