Priority test
benedettoscala/CiviConnect pull request #25
Opened 2024-12-14 16:22 UTC by Marco-Brescia

This pull request includes several changes to the `MunicipalityReportManagementController` class, the `PriorityReport` enum, and the addition of new test cases. The most important changes include refactoring the controller's constructor, adding validation for priority changes, and updating the test suite to cover new scenarios.

### Refactoring and Constructor Improvements:

* [`src/lib/gestione_segnalazione_comune/gestione_segnalazione_comune_controller.dart`](diffhunk://#diff-baca7b9053e316539b9fa57db40b4446aa7b969f5480d5c460e19d80b8c7fd83L43-R79): Refactored the constructor of `MunicipalityReportManagementController` to accept DAOs as parameters, allowing for better dependency injection and testing. A new constructor `MunicipalityReportManagementController.forTest` was added for testing purposes.

### Priority Change Validation:

* [`src/lib/gestione_segnalazione_comune/gestione_segnalazione_comune_controller.dart`](diffhunk://#diff-baca7b9053e316539b9fa57db40b4446aa7b969f5480d5c460e19d80b8c7fd83L139-R166): Added validation to the `editReportPriority` method to ensure that only valid priority levels (`high`, `medium`, `low`) are accepted. An error message is shown for invalid priorities.

### Enum Value Update:

* [`src/lib/utils/report_status_priority.dart`](diffhunk://#diff-94d444312a4c819995611bf402f02d5364d069d10898b70894cb405909d52e93L70-R70): Updated the `PriorityReport` enum to correct the value of `low` priority from 1 to 2.

### Test Suite Enhancements:

* [`src/test/select_priority_test.dart`](diffhunk://#diff-7f2b0f44118b43dd5cbcee7d31f51d58dd28e8d93e77e5f045db7c8444ee9f1eR1-R128): Added new test cases to cover the `editReportPriority` method, including scenarios where the priority is not changed and where it is successfully updated. Mock classes and a fake DAO were introduced to facilitate testing.

2024-12-14 16:37 UTC, Luigi11162 approved these changes
Good Test! Approved

2024-12-14 16:54 UTC, benedettoscala approved these changes
LGTM!

2024-12-14 17:15 UTC, Type-Here requested changes

2024-12-14 17:15 UTC, Type-Here commented on src/lib/gestione_segnalazione_comune/gestione_segnalazione_comune_controller.dart
> +  MunicipalityReportManagementController({rdao, udao, this.redirectPage, context})
Naming doesn't respect style and it is too obscure

2024-12-14 17:15 UTC, Type-Here commented on src/lib/gestione_segnalazione_comune/gestione_segnalazione_comune_controller.dart
> -          message: 'Priorità segnalazione cambiata',
No change of state/ color /styling between error and info message

2024-12-14 17:15 UTC, Type-Here commented on src/test/select_priority_test.dart
> +    testWidgets('editReportPriority changes the priority', (tester) async {
Redundant code. 1 different variable can be passed as parameter of an extracted method

2024-12-14 17:38 UTC, Marco-Brescia commented on src/lib/gestione_segnalazione_comune/gestione_segnalazione_comune_controller.dart
> -          message: 'Priorità segnalazione cambiata',
Non ho capito

2024-12-14 21:11 UTC, Borax-Gargamella commented on src/lib/gestione_segnalazione_comune/gestione_segnalazione_comune_controller.dart
> -          message: 'Priorità segnalazione cambiata',
Both error and success messages are displayed in the snackbar as if they were success messages because the isError field is not set to true for error messages.

2024-12-14 21:42 UTC, Marco-Brescia commented on src/lib/gestione_segnalazione_comune/gestione_segnalazione_comune_controller.dart
> +  MunicipalityReportManagementController({rdao, udao, this.redirectPage, context})
fixed

2024-12-14 21:42 UTC, Marco-Brescia commented on src/lib/gestione_segnalazione_comune/gestione_segnalazione_comune_controller.dart
> -          message: 'Priorità segnalazione cambiata',
Ok, I think i fixed.

2024-12-14 22:25 UTC, Borax-Gargamella approved these changes
👍

2024-12-15 00:51 UTC, Type-Here approved these changes
showMessage isError could be simplified no need for if else statement but a conditional value on the parameter could be enough. Anyway good job on the testing part

2024-12-15 00:51 UTC, merged